// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiLIuRB59ArKqGnUbuQjzVNL_3TFu_VrU',
    appId: '1:82142778965:web:9545da8f51cd65c9f6e6dc',
    messagingSenderId: '82142778965',
    projectId: 'crudtry-a2c16',
    authDomain: 'crudtry-a2c16.firebaseapp.com',
    storageBucket: 'crudtry-a2c16.firebasestorage.app',
    measurementId: 'G-EGEND4VHZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsWVC_lKOU6QCNaWuFH9q95H22uZR8IAM',
    appId: '1:82142778965:android:e96f17a17d7dfd51f6e6dc',
    messagingSenderId: '82142778965',
    projectId: 'crudtry-a2c16',
    storageBucket: 'crudtry-a2c16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCx3ll8egsnxQOBagArBPi0QmviIlZBZw',
    appId: '1:82142778965:ios:13070f607c6be408f6e6dc',
    messagingSenderId: '82142778965',
    projectId: 'crudtry-a2c16',
    storageBucket: 'crudtry-a2c16.firebasestorage.app',
    iosBundleId: 'com.example.flutterTry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCx3ll8egsnxQOBagArBPi0QmviIlZBZw',
    appId: '1:82142778965:ios:13070f607c6be408f6e6dc',
    messagingSenderId: '82142778965',
    projectId: 'crudtry-a2c16',
    storageBucket: 'crudtry-a2c16.firebasestorage.app',
    iosBundleId: 'com.example.flutterTry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiLIuRB59ArKqGnUbuQjzVNL_3TFu_VrU',
    appId: '1:82142778965:web:75f2f84c48b47c00f6e6dc',
    messagingSenderId: '82142778965',
    projectId: 'crudtry-a2c16',
    authDomain: 'crudtry-a2c16.firebaseapp.com',
    storageBucket: 'crudtry-a2c16.firebasestorage.app',
    measurementId: 'G-1NNQMR8XF7',
  );
}
